laravel/app/Http/routes.php
<?php 

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@home');
Route::get('/about', 'HomeController@about');

Route::get('/user/create', 'UserController@create');
Route::post('user/login', array('as' => 'user.login', 'uses' => 'UserController@login'));
Route::get('user/logout', array('as' => 'user.logout', 'uses' => 'UserController@logout'));
Route::get('user/signin', array('as' => 'user.signin', 'uses' => 'UserController@signin'));


Route::get('speaker/{id}', 'SpeakerController@index');
Route::resource('speaker', 'SpeakerController');

Route::get("test", 'testingController@index');

// Only logged in Users are allowed here:



Route::group(array('middleware' => 'auth'), function()
{
    Route::get('schedule/{schedule_id}', 'UserController@joinActivity');
    Route::get('schedule/{schedule_id}/leave', 'UserController@leaveActivity');
    
    Route::get('user/schedule', array('as' => 'user.schedule', 'uses' => 'UserController@schedule'));
});


// Do these need to be protected by auth? Put in above Route group if yes.
Route::resource('schedule', 'ActivityController');
Route::resource('user', 'UserController');


// Only Admins are allowed here:
Route::group(['middleware' => 'owner'], function () {
    Route::get('admin', array('as' => 'admin.index', 'uses' => 'AdminController@index'));
    Route::get('admin/activities', array('as' => 'admin.activities.index', 'uses' => 'AdminController@activities'));
    Route::get('admin/speakers', array('as' => 'admin.speakers.index', 'uses' => 'AdminController@speakers'));
    Route::get('admin/users', array('as' => 'admin.users.index', 'uses' => 'AdminController@users'));
    Route::get('admin/activity_speaker', array('as' => 'admin.activities.addSpeaker', 'uses' => 'AdminController@activity_speaker'));
    Route::get('admin/users/edit/{id}', 'AdminController@editUser');
    Route::get('admin/activities/edit/{id}', 'ActivityController@edit');
    Route::get('admin/activities/printActivities', 'ActivityController@printActivities'); 
    Route::get('user/schedule/printUserActivities', 'UserController@printUserActivities'); 
    Route::get('admin/activities/printActivityUsers/{id}', 'ActivityController@printActivityUsers'); 
    Route::get('admin/speakers/edit/{id}', 'SpeakerController@edit');
    Route::get('activity_delete/{id}', 'ActivityController@destroy');
    Route::get('activity_delete_user/{activityId}/{userId}', 'ActivityController@deleteUser');
    Route::get('speaker_delete/{id}', 'SpeakerController@destroy');
    Route::get('user_delete/{id}', 'UserController@destroy');
    Route::post('addSpeakerToActivity/{id}', array('as' => 'admin.activities.addSpeakerToActivity', 'uses' => 'ActivityController@addSpeaker'));
    Route::get('deleteSpeakerFromActivity/{activityId}/{SpeakerId}', array('as' => 'admin.activities.deleteSpeakerFromActivity', 'uses' => 'ActivityController@deleteSpeaker'));
});

laravel/resources/views/home.blade.php
@extends('master')

@section('header')

    <style>
  .demo-card-wide.mdl-card {
    width: 512px;
  }
  .demo-card-wide > .mdl-card__title {
    color: #fff;
    height: 176px;
    background: url('https://lh3.googleusercontent.com/TT-dpPiR8U_EhkoHpglhLIylzqFgpovTi73RpDeLQzU=w533-h400-no') center / cover;
  }
  .demo-card-wide > .mdl-card__menu {
    color: #fff;
  }
    .demo-card-square.mdl-card {
    width: 320px;
    height: 320px;
  }
  .demo-card-square > .mdl-card__title {
    color: #fff;
    background:
      url('https://lh3.googleusercontent.com/tFRjq5nyrNmpSyF3UNb7cBkk1zDioKR7gcldcKSU_aw=w355-h215-no') bottom right 15% no-repeat #46B6AC;
  }
</style>
    @stop

@section('main')
<div class="mdl-cell mdl-cell--4-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>

<div class="mdl-card mdl-shadow--2dp demo-card-wide mdl-cell mdl-cell--6-col">
  <div class="mdl-card__title">
    <h2 class="mdl-card__title-text">Welcome</h2>
  </div>
  <div class="mdl-card__supporting-text">
    The Griffith Student Leadership Conference (SLC) Scheduler is a place for you to add the presentations and workshops you wish to attend. You can then view the personalised schedule on your phone or print a PDF version.
  </div>
  <div class="mdl-card__actions mdl-card--border">
    <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
      Get Started
    </a>
  </div>
</div>


@stop

laravel/resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- This stuff is to support mobile web browsers -->
    <!-- Google -->
    <link rel="manifest" href="manifest.json">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="nice-highres.png">
    <!-- Apple -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    
    <!-- MDL CSS -->
    <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.1/material.red-blue.min.css" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="/laravel/public/css/style.css">
    
    <!-- Google Analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    
      ga('create', 'UA-67318620-1', 'auto');
      ga('send', 'pageview');
  
    </script>
    
    @yield('header')
  </head>
  
  <body>   
     <!-- Always shows a header, even in smaller screens. -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <span class="mdl-layout-title">Griffith SLC Scheduler</span>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <!-- Navigation. We hide it in small screens. -->
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            @if (Auth::check())
            <a class="mdl-navigation__link">Hi, {{Auth::user()->name}}</a>
            <a class="mdl-navigation__link" href="{{ URL::route('user.schedule')}}">Personal Schedule</a>
            @else
            <a class="mdl-navigation__link" href="{{ URL::route('user.signin')}}">Sign In</a>
            <a class="mdl-navigation__link" href="{{ URL::route('user.create')}}">Sign Up</a>
            @endif
            <a class="mdl-navigation__link" href="{{ URL::route('schedule.index')}}">Full Schedule</a>
          </nav>
        </div>
      </header>
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">SLC Scheduler</span>
        <nav class="mdl-navigation">
          <a class="mdl-navigation__link" href="/">Home</a>
          <a class="mdl-navigation__link" href="{{ URL::route('schedule.index')}}">Full Schedule</a>
          @if (Auth::check())
          <a class="mdl-navigation__link" href="{{ URL::route('user.schedule')}}">Personal Schedule</a>
          <a class="mdl-navigation__link" href="{{ URL::route('user.logout')}}">Sign Out</a>
          @else
          <a class="mdl-navigation__link" href="{{ URL::route('user.signin')}}">Sign In</a>
          @endif
          <div class="mdl-layout-spacer"></div>
          <a class="mdl-navigation__link" href="/laravel/public/about">About</a>
          @if (Auth::check()) @if (Auth::user()->group == 'Admin') <a class="mdl-navigation__link" href="{{ URL::route('admin.index')}}">Admin</a> @endif @endif
        </nav>
      </div>
      
        
    
    <main class="mdl-layout__content">
  <div class="demo-container mdl-grid">
        
     @yield('main')
     </div>
    
    @yield('footer')

    </main>
     </div>
    @section('button')
    @show
    <!-- MDL Scripts -->
    <script src="https://storage.googleapis.com/code.getmdl.io/1.0.1/material.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  @yield('modal')
  </body>
  
  </html>

laravel/resources/views/pdf.blade.php
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.1/material.red-blue.min.css" />
        <link rel="stylesheet" href="/laravel/public/css/style.css">
        <style>
        table {
            width: 100%;
        }
        
        </style>
    </head>
    <body>
        
        <h3>Griffith Student Leadership Conference</h3>
        <h5>Personal Schedule for {!! $user !!}</h5>
        <br>
        <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp mdl-cell--12-col full-width">
            <thead>
                <tr>
                  <th>Time</th>
                  <th class="mdl-data-table__cell--non-numeric full-width">Title</th>
                  <th>Speaker</th>
                  <th>Room</th>
            </thead>
            <tbody>
            @foreach($activities as $a)    
               <tr>
                  <td>{!! $a->startingTime !!}</td>
                  <td class="mdl-data-table__cell--non-numeric full-width">{!! $a->title !!}</td>
                  <td>@foreach ($a['speakers'] as $key => $s) {{$s->name}} @if($key != count($a['speakers'])-1)  ,<br>  @endif @endforeach</td>
                  <td>{!! $a->location !!}</td>
               </tr>
            @endforeach
                 
             </tbody>
    </table>
</body>
</html>

laravel/resources/views/testing.blade.php
<html>
    <head>
        <title>This page is used for testing</title>
        <link href='//fonts.googleapis.com/css?family=Lato:100' rel='stylesheet' type='text/css'>

        <style>
            body {
                margin: 0;
                padding: 0;
                width: 100%;
                height: 100%;
                color: #B0BEC5;
                display: table;
                font-weight: 100;
                font-family: 'Lato';
            }

            .container {
                margin-top: 100px;
                text-align: center;
                display: table-cell;
            }

            .content {
                text-align: center;
                display: inline-block;
            }

            .title {
                font-size: 96px;
                margin-bottom: 40px;
            }

            .quote {
                color: #222;
                text-align: left;
                width: 80%;
                margin: auto;
                font-size: 20px;
            }
            
            .quote .red {
                color: red;
                margin-right: 20px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="content">
                <div class="title">Testing</div>
                <div class="quote">
                    <p><strong class="red">Users-example    : </strong> {{ $data['user'] }}</p>
                    <p><strong class="red">Speaker-example  : </strong> {{ $data['speaker'] }}</p>
                    <p><strong class="red">Activity-example : </strong> {{ $data['activity'] }}</p>
                    <p><strong class="red">Accessing M-M table : </strong> {{ $data['pivot'] }}</p>
                    <p><strong class="red">Saving M-M table : </strong> <br>$activity = new Activity; <br> $user  = User::find($id); <br> $user->activities()->save($activity);</p>
                </div>
            </div>
        </div>
    </body>
</html>